/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_artoolkit_artank_Simulation */

#ifndef _Included_br_artoolkit_artank_Simulation
#define _Included_br_artoolkit_artank_Simulation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation_shutdown
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    shot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation_shot
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    _cannonUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation__1cannonUp
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    _cannonDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation__1cannonDown
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation_reset
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation_initialise
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_Simulation
 * Method:    running
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_Simulation_running
  (JNIEnv *, jobject object);

#ifdef __cplusplus
}
#endif
#endif
