/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_artoolkit_artank_ARTankRenderer */

#ifndef _Included_br_artoolkit_artank_ARTankRenderer
#define _Included_br_artoolkit_artank_ARTankRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     br_artoolkit_artank_ARTankRenderer
 * Method:    surfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_ARTankRenderer_surfaceCreated
  (JNIEnv *, jobject object);

/*
 * Class:     br_artoolkit_artank_ARTankRenderer
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_ARTankRenderer_surfaceChanged
  (JNIEnv *, jobject object, jint, jint);

/*
 * Class:     br_artoolkit_artank_ARTankRenderer
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_br_artoolkit_artank_ARTankRenderer_drawFrame
  (JNIEnv *, jobject object);

#ifdef __cplusplus
}
#endif
#endif
